main:
	g++ -std=c++11 \
	main.cpp \
	DumbTimer.h DumbTimer.cpp \
	DerivePlayersOnCourt.h DerivePlayersOnCourt.cpp \
	DerivePlayerDetails.h DerivePlayerDetails.cpp \
	GameHolder.h GameHolder.cpp \
	GameLoader.h GameLoader.cpp \
	Play.h Play.cpp \
	-o program
